# 自动更新
auto-update: true

# 是否向客户端发送已安装的附属列表? (默认: true)
automatic-addons: true

# 哪些附属不应该发送到客户端。仅在 automatic-addons 为 true
addon-blacklist: []

# 是否向客户端发包以启用自定义方块材质? (默认: true)
custom-block-textures: true